version: '3.8'

services:
  app:
    build: .
    container_name: network_asset_reconciliation
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
